### ISSUE TITLE
Not using env shebang

### ISSUE THREAD

**Issue by ammgws** [WnndGws/wyman#1]
https://github.com/WnndGws/wyman/blob/2159da77707d23c5b4b9aeda28d87983ab93c3d4/wyman.py#L1

Same as https://github.com/WnndGws/Agendrum/issues/14

**Comment by WnndGws** [comment]
Will address soon

**Comment by ammgws** [comment]
When

**Comment by ammgws** [comment]
Preemptive closure since this will be fixed by you tonight
